project_id = "ekprysxfgkafpwjbocab"

[functions.debito-webhook]
enabled = true
verify_jwt = false

[functions.handle-2fa]
enabled = true
verify_jwt = true
import_map = "./functions/handle-2fa/deno.json"
entrypoint = "./functions/handle-2fa/index.ts"

[functions.send-library-code]
enabled = true
verify_jwt = true
import_map = "./functions/send-library-code/deno.json"
entrypoint = "./functions/send-library-code/index.ts"

[functions.verify-library-code]
enabled = true
verify_jwt = true
import_map = "./functions/verify-library-code/deno.json"
entrypoint = "./functions/verify-library-code/index.ts"

[functions.check-all-orders]
enabled = true
verify_jwt = true
import_map = "./functions/check-all-orders/deno.json"
entrypoint = "./functions/check-all-orders/index.ts"

[functions.abandoned-cart-recovery]
enabled = true
verify_jwt = true
import_map = "./functions/abandoned-cart-recovery/deno.json"
entrypoint = "./functions/abandoned-cart-recovery/index.ts"
